use num_enum::{IntoPrimitive, TryFromPrimitive};
use std::fmt::{Display, Formatter};

pub const TEAMS: [Team; 31] = [
    Team::All,
    Team::ArizonaDiamondbacks,
    Team::AtlantaBraves,
    Team::BaltimoreOrioles,
    Team::BostonRedSox,
    Team::ChicagoCubs,
    Team::ChicagoWhiteSox,
    Team::CincinnatiReds,
    Team::ClevelandGuardians,
    Team::ColoradoRockies,
    Team::DetroitTigers,
    Team::HoustonAstros,
    Team::KansasCityRoyals,
    Team::LosAngelesAngels,
    Team::LosAngelesDodgers,
    Team::MiamiMarlins,
    Team::MilwaukeeBrewers,
    Team::MinnesotaTwins,
    Team::NewYorkMets,
    Team::NewYorkYankees,
    Team::OaklandAthletics,
    Team::PhiladelphiaPhillies,
    Team::PittsburghPirates,
    Team::SanDiegoPadres,
    Team::SanFranciscoGiants,
    Team::SeattleMariners,
    Team::StLouisCardinals,
    Team::TampaBayRays,
    Team::TexasRangers,
    Team::TorontoBlueJays,
    Team::WashingtonNationals,
];

#[derive(IntoPrimitive, TryFromPrimitive, Copy, Clone, PartialEq)]
#[repr(u16)]
pub enum Team {
    All = 0,
    ArizonaDiamondbacks = 109,
    AtlantaBraves = 144,
    BaltimoreOrioles = 110,
    BostonRedSox = 111,
    ChicagoCubs = 112,
    ChicagoWhiteSox = 145,
    CincinnatiReds = 113,
    ClevelandGuardians = 114,
    ColoradoRockies = 115,
    DetroitTigers = 116,
    HoustonAstros = 117,
    KansasCityRoyals = 118,
    LosAngelesAngels = 108,
    LosAngelesDodgers = 119,
    MiamiMarlins = 146,
    MilwaukeeBrewers = 158,
    MinnesotaTwins = 142,
    NewYorkMets = 121,
    NewYorkYankees = 147,
    OaklandAthletics = 133,
    PhiladelphiaPhillies = 143,
    PittsburghPirates = 134,
    SanDiegoPadres = 135,
    SanFranciscoGiants = 137,
    SeattleMariners = 136,
    StLouisCardinals = 138,
    TampaBayRays = 139,
    TexasRangers = 140,
    TorontoBlueJays = 141,
    WashingtonNationals = 120,
}

impl Display for Team {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Team::All => write!(f, "All"),
            Team::ArizonaDiamondbacks => write!(f, "Arizona Diamondbacks"),
            Team::AtlantaBraves => write!(f, "Atlanta Braves"),
            Team::BaltimoreOrioles => write!(f, "Baltimore Orioles"),
            Team::BostonRedSox => write!(f, "Boston Red Sox"),
            Team::ChicagoCubs => write!(f, "Chicago Cubs"),
            Team::ChicagoWhiteSox => write!(f, "Chicago White Sox"),
            Team::CincinnatiReds => write!(f, "Cincinnati Reds"),
            Team::ClevelandGuardians => write!(f, "Cleveland Guardians"),
            Team::ColoradoRockies => write!(f, "Colorado Rockies"),
            Team::DetroitTigers => write!(f, "Detroit Tigers"),
            Team::HoustonAstros => write!(f, "Houston Astros"),
            Team::KansasCityRoyals => write!(f, "Kansas City Royals"),
            Team::LosAngelesAngels => write!(f, "Los Angeles Angels"),
            Team::LosAngelesDodgers => write!(f, "Los Angeles Dodgers"),
            Team::MiamiMarlins => write!(f, "Miami Marlins"),
            Team::MilwaukeeBrewers => write!(f, "Milwaukee Brewers"),
            Team::MinnesotaTwins => write!(f, "Minnesota Twins"),
            Team::NewYorkMets => write!(f, "New York Mets"),
            Team::NewYorkYankees => write!(f, "New York Yankees"),
            Team::OaklandAthletics => write!(f, "Oakland Athletics"),
            Team::PhiladelphiaPhillies => write!(f, "Philadelphia Phillies"),
            Team::PittsburghPirates => write!(f, "Pittsburgh Pirates"),
            Team::SanDiegoPadres => write!(f, "San Diego Padres"),
            Team::SanFranciscoGiants => write!(f, "San Francisco Giants"),
            Team::SeattleMariners => write!(f, "Seattle Mariners"),
            Team::StLouisCardinals => write!(f, "St. Louis Cardinals"),
            Team::TampaBayRays => write!(f, "Tampa Bay Rays"),
            Team::TexasRangers => write!(f, "Texas Rangers"),
            Team::TorontoBlueJays => write!(f, "Toronto Blue Jays"),
            Team::WashingtonNationals => write!(f, "Washington Nationals"),
        }
    }
}
